// packages/react/src/hook/use-layn.ts
import {
  CONTAINER_TAB_INDEX,
  containerAria,
  contentAria,
  createStore,
  resolveEngineConfig,
} from '@laynjs/adapter-utils'
import { createEngine, diffItems, type ItemId, type LayoutEngine } from '@laynjs/core'
import { type BindOptions, bindEngine, type EngineBinding } from '@laynjs/dom'
import {
  type CSSProperties,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useSyncExternalStore,
} from 'react'
import { buildItems } from '../items/index.js'
import type { UseLaynOptions, UseLaynResult } from '../types/index.js'
import { useConstant } from './use-constant.js'

const containerStyle: CSSProperties = { position: 'relative', overflow: 'auto' }

const contentStyle = (width: number, height: number): CSSProperties => ({
  position: 'relative',
  width,
  height,
})

export const useLayn = <TData = unknown>(options: UseLaynOptions<TData>): UseLaynResult<TData> => {
  const axis = options.axis ?? 'vertical'
  const overscan = options.overscan ?? 0
  const environment = options.environment

  const engine = useConstant<LayoutEngine>(() =>
    createEngine(
      resolveEngineConfig({
        algorithm: options.algorithm,
        items: options.items,
        gap: options.gap,
        viewport: options.viewport,
        measurements: options.measurements,
      }),
    ),
  )
  const store = useConstant(() => createStore(engine, axis, overscan))
  const bindingRef = useRef<EngineBinding | undefined>(undefined)
  const refCache = useConstant(() => new Map<ItemId, (element: HTMLElement | null) => void>())

  const state = useSyncExternalStore(store.subscribe, store.getState, store.getState)

  useEffect(() => {
    engine.setAlgorithm(options.algorithm)
  }, [engine, options.algorithm])

  const gapX = options.gap?.x ?? 0
  const gapY = options.gap?.y ?? 0
  useEffect(() => {
    engine.setGap({ x: gapX, y: gapY })
  }, [engine, gapX, gapY])

  useEffect(() => {
    if (diffItems(engine.getSnapshot().items, options.items).kind !== 'identical') {
      engine.setItems(options.items)
    }
  }, [engine, options.items])

  useEffect(() => {
    const live = new Set<ItemId>(options.items.map((item) => item.id))
    for (const id of refCache.keys()) {
      if (!live.has(id)) {
        refCache.delete(id)
      }
    }
  }, [options.items, refCache])

  useEffect(
    () => () => {
      bindingRef.current?.destroy()
      store.destroy()
    },
    [store],
  )

  const containerRef = useCallback(
    (element: HTMLElement | null): void => {
      if (element === null) {
        bindingRef.current?.destroy()
        bindingRef.current = undefined
        return
      }
      const bindOptions: BindOptions = {
        scroll: element,
        axis,
        overscan,
        ...(environment !== undefined ? { environment } : {}),
      }
      const binding = bindEngine(engine, bindOptions)
      bindingRef.current = binding
      store.attach(binding)
    },
    [engine, store, axis, overscan, environment],
  )

  const refFor = useCallback(
    (id: ItemId) => {
      const existing = refCache.get(id)
      if (existing !== undefined) {
        return existing
      }
      const ref = (element: HTMLElement | null): void => {
        if (element !== null) {
          bindingRef.current?.observeItem(id, element)
        } else {
          bindingRef.current?.unobserveItem(id)
        }
      }
      refCache.set(id, ref)
      return ref
    },
    [refCache],
  )

  const items = useMemo(
    () => buildItems(options.items, state.snapshot, state.visible, refFor),
    [options.items, state, refFor],
  )

  const contentProps = useMemo(
    () => ({
      ...contentAria(),
      style: contentStyle(state.snapshot.contentSize.width, state.snapshot.contentSize.height),
    }),
    [state.snapshot.contentSize.width, state.snapshot.contentSize.height],
  )

  return {
    containerProps: {
      ref: containerRef,
      style: containerStyle,
      tabIndex: CONTAINER_TAB_INDEX,
      ...containerAria(options.label),
    },
    contentProps,
    items,
    totalSize: state.snapshot.contentSize,
    engine,
  }
}

// packages/angular/src/layn/use-layn.ts
import { computed, DestroyRef, inject, signal } from '@angular/core'
import {
  containerAttrs,
  contentAria,
  contentStyleObject,
  createStore,
  resolveEngineConfig,
} from '@laynjs/adapter-utils'
import {
  createEngine,
  diffItems,
  type Gap,
  type ItemId,
  type LayoutAlgorithm,
  type LayoutItem,
} from '@laynjs/core'
import { type BindOptions, bindEngine, type EngineBinding } from '@laynjs/dom'
import { buildItems } from '../items/index.js'
import type { LaynRef, UseLaynOptions } from '../types/index.js'

const containerStyle: Record<string, string> = { position: 'relative', overflow: 'auto' }

export const useLayn = <TData = unknown>(options: UseLaynOptions<TData>): LaynRef<TData> => {
  const destroyRef = inject(DestroyRef)
  const axis = options.axis ?? 'vertical'
  const overscan = options.overscan ?? 0
  const environment = options.environment

  const engine = createEngine(
    resolveEngineConfig({
      algorithm: options.algorithm,
      items: options.items,
      gap: options.gap,
      viewport: options.viewport,
      measurements: options.measurements,
    }),
  )
  const store = createStore(engine, axis, overscan)
  const state = signal(store.getState())
  const unsubscribe = store.subscribe(() => state.set(store.getState()))

  let binding: EngineBinding | undefined
  let currentItems: readonly LayoutItem<TData>[] = options.items

  destroyRef.onDestroy(() => {
    unsubscribe()
    binding?.destroy()
    store.destroy()
  })

  return {
    items: computed(() => buildItems(currentItems, state().snapshot, state().visible)),
    contentStyle: computed(() => contentStyleObject(state().snapshot.contentSize)),
    totalSize: computed(() => state().snapshot.contentSize),
    containerStyle,
    containerAttrs: containerAttrs(options.label),
    contentAttrs: contentAria(),
    engine,
    attachContainer: (element: HTMLElement) => {
      const bindOptions: BindOptions = {
        scroll: element,
        axis,
        overscan,
        ...(environment !== undefined ? { environment } : {}),
      }
      binding = bindEngine(engine, bindOptions)
      store.attach(binding)
    },
    observeItem: (id: ItemId, element: HTMLElement) => binding?.observeItem(id, element),
    unobserveItem: (id: ItemId) => binding?.unobserveItem(id),
    setItems: (items) => {
      currentItems = items
      if (diffItems(engine.getSnapshot().items, items).kind !== 'identical') {
        engine.setItems(items)
      }
    },
    setAlgorithm: (algorithm: LayoutAlgorithm) => engine.setAlgorithm(algorithm),
    setGap: (gap: Gap | undefined) => engine.setGap({ x: gap?.x ?? 0, y: gap?.y ?? 0 }),
  }
}
