// examples/vue/src/App.vue
<script setup lang="ts">
import Section from './Section.vue'
import { layouts } from './layouts'
</script>

<template>
  <div style="font-family: system-ui, sans-serif; padding: 24px; max-width: 940px; margin: 0 auto">
    <Section v-for="spec in layouts" :key="spec.id" :spec="spec" />
  </div>
</template>

// examples/solid/src/App.tsx
import { For } from 'solid-js'
import { layouts } from './layouts'
import { Section } from './Section'

export function App() {
  return (
    <div
      style={{
        'font-family': 'system-ui, sans-serif',
        padding: '24px',
        'max-width': '940px',
        margin: '0 auto',
      }}
    >
      <For each={layouts}>{(spec) => <Section spec={spec} />}</For>
    </div>
  )
}
